#include "infra/code_generator_internal.h"

namespace app {

QString sanitizeIdentifier(const QString& raw, bool capitalizeFirst) {
    QString cleaned = raw;
    cleaned.replace(QLatin1Char('*'), QStringLiteral("Wildcard"));
    static const QRegularExpression boundary(QStringLiteral("[^A-Za-z0-9]+"));
    const QStringList tokens = cleaned.split(boundary, Qt::SkipEmptyParts);
    QString result;
    for (int i = 0; i < tokens.size(); ++i) {
        QString token = tokens.at(i);
        // Lowercase all-caps words so "SESSION_COMMITTED" joins as "sessionCommitted".
        bool hasLetter = false;
        bool allLettersUpper = true;
        for (const QChar& c : token) {
            if (c.isLetter()) {
                hasLetter = true;
                if (!c.isUpper()) {
                    allLettersUpper = false;
                    break;
                }
            }
        }
        if (hasLetter && allLettersUpper) {
            token = token.toLower();
        }

        if (i == 0 && !capitalizeFirst) {
            token[0] = token.at(0).toLower();
        } else {
            token[0] = token.at(0).toUpper();
        }
        result += token;
    }
    if (!result.isEmpty() && result.at(0).isDigit()) {
        result.prepend(QLatin1Char('_'));
    }
    return result;
}

QString sanitizeSnakeCase(const QString& raw) {
    QString cleaned = raw;
    cleaned.replace(QLatin1Char('*'), QStringLiteral("wildcard"));
    static const QRegularExpression boundary(QStringLiteral("[^A-Za-z0-9]+"));
    const QStringList tokens = cleaned.split(boundary, Qt::SkipEmptyParts);
    QStringList lowered;
    lowered.reserve(tokens.size());
    for (const QString& token : tokens) {
        lowered.push_back(token.toLower());
    }
    QString result = lowered.join(QStringLiteral("_"));
    if (!result.isEmpty() && result.at(0).isDigit()) {
        result.prepend(QLatin1Char('_'));
    }
    return result;
}


QString bannerLines(const QString& oneLineDescription) {
    return QStringLiteral(
               "// Generated by Ordo State Designer -- regenerated wholesale on every\n"
               "// [Generate C++] click. DO NOT EDIT -- your changes will be overwritten on\n"
               "// the next generation. %1\n"
               "// Implement hooks in the domain/ stubs next to these files: the generator\n"
               "// writes them once and never overwrites them.\n")
        .arg(oneLineDescription);
}

QString openNamespace(const QString& joined) { return QStringLiteral("namespace %1 {\n").arg(joined); }
QString closeNamespace(const QString& joined) { return QStringLiteral("}  // namespace %1\n").arg(joined); }



QString contextTypeSpelling(ContextType type) {
    switch (type) {
        case ContextType::Bool:
            return QStringLiteral("bool");
        case ContextType::Int:
            return QStringLiteral("long long");
        case ContextType::Double:
            return QStringLiteral("double");
        case ContextType::String:
            return QStringLiteral("std::string");
        case ContextType::Object:
            return QStringLiteral("/* object */");
    }
    return QStringLiteral("long long");
}

QString cppPayloadTypeSpelling(const QString& payloadType) {
    if (const auto scalar = builtInPayloadScalar(payloadType)) {
        return contextTypeSpelling(*scalar);
    }
    return payloadType.trimmed();
}

// The C++ type `event` binds to in this row's guard and action, or empty. Per
// ROW from its payloadType, the same rule as the simulator and validator; an
// onDone/onError row binds `output`/`error` instead, never `event`.
QString eventPayloadCppTypeForTransition(const Machine& machine, const Transition& transition) {
    if (transition.payloadType.isEmpty() ||
        invokePayloadKindForTransition(machine, transition) != InvokePayloadKind::None) {
        return QString();
    }
    return cppPayloadTypeSpelling(transition.payloadType);
}

void emitNestedStruct(QString& out, const QJsonObject& obj, const QString& structTypeName,
                      const QString& memberName, int indentLevel) {
    const QString indent(indentLevel * 4, QLatin1Char(' '));
    const QString innerIndent((indentLevel + 1) * 4, QLatin1Char(' '));
    out += indent + QStringLiteral("struct %1 {\n").arg(structTypeName);

    QStringList keys = obj.keys();
    std::sort(keys.begin(), keys.end());

    for (const QString& key : keys) {
        const QJsonValue val = obj.value(key);
        if (val.isBool()) {
            out += innerIndent + QStringLiteral("bool %1 = %2;\n")
                       .arg(key, val.toBool() ? QStringLiteral("true") : QStringLiteral("false"));
        } else if (val.isDouble()) {
            const double num = val.toDouble();
            const bool isInt = std::isfinite(num) && num == std::trunc(num) && std::fabs(num) < 9.2e18;
            if (isInt) {
                out += innerIndent + QStringLiteral("long long %1 = %2;\n")
                           .arg(key, QString::number(static_cast<qint64>(num)));
            } else {
                out += innerIndent + QStringLiteral("double %1 = %2;\n").arg(key, cppDoubleLiteral(num));
            }
        } else if (val.isString()) {
            QString escaped;
            const QString str = val.toString();
            for (const QChar ch : str) {
                const char16_t unit = ch.unicode();
                if (unit == u'\\') {
                    escaped += QLatin1String("\\\\");
                } else if (unit == u'"') {
                    escaped += QLatin1String("\\\"");
                } else if (unit < 0x20 || unit == 0x7f) {
                    escaped += QStringLiteral("\\%1").arg(static_cast<int>(unit), 3, 8, QLatin1Char('0'));
                } else {
                    escaped += ch;
                }
            }
            out += innerIndent + QStringLiteral("std::string %1 = \"%2\";\n").arg(key, escaped);
        } else if (val.isObject()) {
            const QString subStructType = sanitizeIdentifier(key, true) + QStringLiteral("_t");
            emitNestedStruct(out, val.toObject(), subStructType, key, indentLevel + 1);
        }
    }
    out += indent + QStringLiteral("} %1;\n").arg(memberName);
}

// Shortest text that re-parses to the same double, always with a '.' or
// exponent so C++ reads a double (mirrors expr's printDouble()).
QString cppDoubleLiteral(double value) {
    QString text = QString::number(value, 'g', 17);
    for (int precision = 1; precision < 17; ++precision) {
        const QString candidate = QString::number(value, 'g', precision);
        if (candidate.toDouble() == value) {
            text = candidate;
            break;
        }
    }
    if (!text.contains(QLatin1Char('.')) && !text.contains(QLatin1Char('e')) && !text.contains(QLatin1Char('E'))) {
        text.append(QLatin1String(".0"));
    }
    return text;
}

// C++ initialiser for a context variable. Must match the simulator's seeding
// exactly (sim_agent.h), or the generated core starts from a different state:
// Bool "true"/"false" case-insensitive, Int/Double trimmed, String verbatim,
// malformed or non-finite -> the type's zero value. INT64_MIN is spelled as
// two terms: `-9223372036854775808` negates an out-of-range literal.
QString contextInitialiser(const ContextVariable& variable) {
    const QString trimmed = variable.initialValue.trimmed();
    switch (variable.type) {
        case ContextType::Bool:
            return trimmed.compare(QStringLiteral("true"), Qt::CaseInsensitive) == 0 ? QStringLiteral("true")
                                                                                      : QStringLiteral("false");
        case ContextType::Int: {
            bool ok = false;
            const qint64 parsed = trimmed.toLongLong(&ok);
            if (!ok) {
                return QStringLiteral("0");
            }
            if (parsed == std::numeric_limits<qint64>::min()) {
                return QStringLiteral("(-9223372036854775807LL - 1)");
            }
            return QString::number(parsed);
        }
        case ContextType::Double: {
            bool ok = false;
            const double parsed = trimmed.toDouble(&ok);
            if (!ok || !std::isfinite(parsed)) {
                return QStringLiteral("0.0");
            }
            return cppDoubleLiteral(parsed);
        }
        case ContextType::String:
            // Octal escapes, never \x: \x is greedy and would swallow a
            // following hex digit of the text.
            {
                QString out;
                for (const QChar ch : variable.initialValue) {
                    const char16_t unit = ch.unicode();
                    if (unit == u'\\') {
                        out += QLatin1String("\\\\");
                    } else if (unit == u'"') {
                        out += QLatin1String("\\\"");
                    } else if (unit < 0x20 || unit == 0x7f) {
                        out += QStringLiteral("\\%1").arg(static_cast<int>(unit), 3, 8, QLatin1Char('0'));
                    } else {
                        out += ch;
                    }
                }
                return QLatin1Char('"') + out + QLatin1Char('"');
            }
    }
    return QStringLiteral("0");
}


const State* findStateById(const Machine& machine, quint64 id) {
    for (const State& state : machine.states) {
        if (state.id == id) {
            return &state;
        }
    }
    return nullptr;
}

quint64 parentIdOf(const Machine& machine, quint64 stateId) {
    if (stateId == 0) {
        return 0;
    }
    const State* state = findStateById(machine, stateId);
    return state ? state->parentId : 0;
}

bool isAncestorId(const Machine& machine, quint64 ancestorId, quint64 descendantId) {
    if (ancestorId == 0) {
        return true;
    }
    quint64 cur = descendantId;
    while (cur != 0) {
        const quint64 parent = parentIdOf(machine, cur);
        if (parent == ancestorId) {
            return true;
        }
        cur = parent;
    }
    return false;
}

quint64 lccaId(const Machine& machine, quint64 sourceId, quint64 targetId) {
    quint64 anc = parentIdOf(machine, sourceId);
    while (!isAncestorId(machine, anc, targetId)) {
        anc = parentIdOf(machine, anc);
    }
    return anc;
}

quint64 lccaId(const Machine& machine, quint64 sourceId, const QList<quint64>& targetIds) {
    if (targetIds.isEmpty()) {
        return 0;
    }
    quint64 anc = lccaId(machine, sourceId, targetIds.first());
    for (int i = 1; i < targetIds.size(); ++i) {
        while (!isAncestorId(machine, anc, targetIds.at(i))) {
            anc = parentIdOf(machine, anc);
        }
    }
    return anc;
}

int depthOfId(const Machine& machine, quint64 stateId) {
    int depth = 0;
    quint64 cur = parentIdOf(machine, stateId);
    while (cur != 0) {
        ++depth;
        cur = parentIdOf(machine, cur);
    }
    return depth;
}



QString invokeHookMethodName(const QString& effectiveId) {
    return QStringLiteral("start%1").arg(sanitizeIdentifier(effectiveId, /*capitalizeFirst=*/true));
}
QString invokeStopSourceMember(const QString& effectiveId) {
    return sanitizeIdentifier(effectiveId, /*capitalizeFirst=*/false) + QStringLiteral("StopSource_");
}

// ---- the extra-hook-reference chain (Scheduler + Invocations) --------------
// The single home of the optional hooks' parameter order: Scheduler, then
// Invocations. Every core/agent/bootstrap signature goes through these.
QString extraCtorParams(const GenModel& model) {
    QString out;
    if (model.hasScheduler) {
        out += QStringLiteral(", %1Scheduler& scheduler").arg(model.machinePascal);
    }
    if (model.hasInvoke) {
        out += QStringLiteral(", %1Invocations& invocations").arg(model.machinePascal);
    }
    return out;
}
QString extraCtorInit(const GenModel& model) {
    QString out;
    if (model.hasScheduler) {
        out += QStringLiteral(", scheduler_(scheduler)");
    }
    if (model.hasInvoke) {
        out += QStringLiteral(", invocations_(invocations)");
    }
    return out;
}
// Plain-name forwarding (the agent constructor into its core).
QString extraArgForward(const GenModel& model) {
    QString out;
    if (model.hasScheduler) {
        out += QStringLiteral(", scheduler");
    }
    if (model.hasInvoke) {
        out += QStringLiteral(", invocations");
    }
    return out;
}
// std::ref(...) forwarding, for register<Machine>()'s agent construction.
QString extraStdRefForward(const GenModel& model) {
    QString out;
    if (model.hasScheduler) {
        out += QStringLiteral(", std::ref(scheduler)");
    }
    if (model.hasInvoke) {
        out += QStringLiteral(", std::ref(invocations)");
    }
    return out;
}
// The "/`scheduler`/`invocations`" backtick list some header comments splice
// into their own prose.
QString extraRefComment(const GenModel& model) {
    QString out;
    if (model.hasScheduler) {
        out += QStringLiteral("/`scheduler`");
    }
    if (model.hasInvoke) {
        out += QStringLiteral("/`invocations`");
    }
    return out;
}

// ---- guard / action classification and emission ----------------------------
// Classification always goes through expr's isBareIdentifier()/parse*Form(),
// the same functions the validator and simulator use; never mirror the rules.

// True when `guard` becomes a pure-virtual hook rather than inline code: a bare
// identifier always does; an expression does only when there is neither a
// Context nor a payload (`payloadInScope`) to compile it against.


bool guardIsHook(const GenModel& model, const QString& guard, bool payloadInScope) {
    if (expr::isBareIdentifier(guard)) {
        return true;
    }
    return payloadInScope ? false : !model.hasContext;
}

// An action is a hook only when no action form (sendTo, sendParent, raise,
// assign) claims it, valid or malformed.
bool actionIsHook(const GenModel& model, const QString& action, bool payloadInScope) {
    const expr::SendToForm sendToForm = expr::parseSendToForm(action);
    if (sendToForm.ok || !sendToForm.message.isEmpty()) {
        return false;
    }
    const expr::SendParentForm sendParentForm = expr::parseSendParentForm(action);
    if (sendParentForm.ok || !sendParentForm.message.isEmpty()) {
        return false;
    }
    const expr::RaiseForm raiseForm = expr::parseRaiseForm(action);
    if (raiseForm.ok || !raiseForm.message.isEmpty()) {
        return false;
    }
    if (!payloadInScope && !model.hasContext) {
        return true;
    }
    const expr::AssignForm form = expr::parseAssignForm(action);
    return !form.ok && form.message.isEmpty();
}

QString eventEnumIdent(const GenModel& model, const QString& rawEvent) {
    if (model.eventEnumIdentByRaw.contains(rawEvent)) {
        return model.eventEnumIdentByRaw.value(rawEvent);
    }
    for (const QString& existing : model.eventOrder) {
        if (existing.compare(rawEvent, Qt::CaseInsensitive) == 0) {
            return model.eventEnumIdentByRaw.value(existing);
        }
    }
    return sanitizeIdentifier(rawEvent, true);
}

// The C++ condition for a trimmed, non-blank guard, optionally negated.
// `bareIdentifiers` names the row's payload parameter ("output", "error" or
// "event"), if any; non-empty also means the payload is in scope.
QString guardCondition(const GenModel& model, const QString& guard, bool negated,
                        const QSet<QString>& bareIdentifiers) {
    const QString prefix = negated ? QStringLiteral("!") : QString();
    if (guardIsHook(model, guard, !bareIdentifiers.isEmpty())) {
        return prefix + QStringLiteral("guards_.get().%1(%2)")
                            .arg(model.guards.idOf(guard),
                                 model.hasContext ? QLatin1String(kContextMember) : QLatin1String(""));
    }
    const expr::ParseResult parsed = expr::parse(guard);
    if (!parsed.ok) {
        // An unparseable guard is false, as in the simulator.
        return negated ? QStringLiteral("true") : QStringLiteral("false");
    }
    const QString emitted = expr::emitCpp(parsed.ast, QLatin1String(kContextMember), bareIdentifiers);
    return negated ? QStringLiteral("!(%1)").arg(emitted) : emitted;
}

// The one statement an action becomes, or empty for "emit nothing": a
// malformed form, an unknown assign target or an unparseable RHS (validator
// errors the simulator also skips). `bareIdentifiers` as in guardCondition().
QString actionStatement(const GenModel& model, const QString& action, const QSet<QString>& bareIdentifiers) {
    const expr::SendToForm sendToForm = expr::parseSendToForm(action);
    if (sendToForm.ok) {
        return QStringLiteral("actions_.get().%1(%2);")
            .arg(model.actions.idOf(action),
                 model.hasContext ? QLatin1String(kContextMember) : QLatin1String(""));
    }
    if (!sendToForm.message.isEmpty()) {
        return QString();
    }
    const expr::SendParentForm sendParentForm = expr::parseSendParentForm(action);
    if (sendParentForm.ok) {
        return QStringLiteral("actions_.get().%1(%2);")
            .arg(model.actions.idOf(action),
                 model.hasContext ? QLatin1String(kContextMember) : QLatin1String(""));
    }
    if (!sendParentForm.message.isEmpty()) {
        return QString();
    }
    if (actionIsHook(model, action, !bareIdentifiers.isEmpty())) {
        return QStringLiteral("actions_.get().%1(%2);")
            .arg(model.actions.idOf(action),
                 model.hasContext ? QLatin1String(kContextMember) : QLatin1String(""));
    }
    const expr::RaiseForm raiseForm = expr::parseRaiseForm(action);
    if (raiseForm.ok) {
        return QStringLiteral("raise(Event::%1);").arg(eventEnumIdent(model, raiseForm.event));
    }
    if (!raiseForm.message.isEmpty()) {
        return QString();  // malformed raise
    }
    const expr::AssignForm form = expr::parseAssignForm(action);
    if (!form.ok) {
        return QString();  // malformed assign
    }
    const ContextVariable* target = nullptr;
    const QString rootName = form.rootTarget();
    for (const ContextVariable& variable : model.context) {
        if (variable.name == rootName) {
            target = &variable;
            break;
        }
    }
    if (target == nullptr) {
        return QString();
    }
    const expr::ParseResult rhs = expr::parse(form.valueSource);
    if (!rhs.ok) {
        return QString();
    }
    const QString value = expr::emitCpp(rhs.ast, QLatin1String(kContextMember), bareIdentifiers);

    if (!form.isMemberAssign()) {
        switch (target->type) {
            case ContextType::Int:
                // Always cast: matches the simulator's truncation of a Double
                // RHS without inferring the RHS type here.
                return QStringLiteral("%1.%2 = static_cast<long long>(%3);")
                    .arg(QLatin1String(kContextMember), target->name, value);
            case ContextType::Double:
                // Matches the simulator's Int -> Double promotion.
                return QStringLiteral("%1.%2 = static_cast<double>(%3);")
                    .arg(QLatin1String(kContextMember), target->name, value);
            case ContextType::Bool:
            case ContextType::String:
            case ContextType::Object:
                // No coercion: a type mismatch is a validator error and should
                // fail to compile rather than be dropped silently.
                return QStringLiteral("%1.%2 = %3;").arg(QLatin1String(kContextMember), target->name, value);
        }
        return QString();
    }

    // Member assign (e.g. user.age = 25 or user.profile.score = 99.5)
    QJsonParseError err;
    const QJsonDocument jsonDoc = QJsonDocument::fromJson(target->initialValue.trimmed().toUtf8(), &err);
    bool isInt = false;
    bool isDouble = false;
    if (!jsonDoc.isNull() && jsonDoc.isObject()) {
        const QStringList segments = form.memberPath().split(QLatin1Char('.'));
        QJsonObject curr = jsonDoc.object();
        for (int i = 0; i < segments.size(); ++i) {
            const QString& seg = segments.at(i);
            if (!curr.contains(seg)) break;
            const QJsonValue v = curr.value(seg);
            if (i == segments.size() - 1) {
                if (v.isDouble()) {
                    const double num = v.toDouble();
                    isInt = std::isfinite(num) && num == std::trunc(num) && std::fabs(num) < 9.2e18;
                    isDouble = !isInt;
                }
            } else if (v.isObject()) {
                curr = v.toObject();
            } else {
                break;
            }
        }
    }

    if (isInt) {
        return QStringLiteral("%1.%2 = static_cast<long long>(%3);")
            .arg(QLatin1String(kContextMember), form.target, value);
    }
    if (isDouble) {
        return QStringLiteral("%1.%2 = static_cast<double>(%3);")
            .arg(QLatin1String(kContextMember), form.target, value);
    }
    return QStringLiteral("%1.%2 = %3;").arg(QLatin1String(kContextMember), form.target, value);
}

// Appends one action's statement at `indent`, or nothing when it emits nothing.
void appendAction(QString& text, const GenModel& model, const QString& indent, const QString& action,
                   const QSet<QString>& bareIdentifiers) {
    const QString statement = actionStatement(model, action, bareIdentifiers);
    if (!statement.isEmpty()) {
        text += indent + statement + QStringLiteral("\n");
    }
}

// Context accessors, identical in the flat and hierarchical cores.
QString contextAccessorLines() {
    return QStringLiteral(
        "    // The machine's live extended state. An owner reads it to render, and\n"
        "    // may seed it before the first event -- but every write DURING a run\n"
        "    // belongs to an assign or an action hook, or the core's own firing and\n"
        "    // the owner's writes interleave in an order nothing documents.\n"
        "    Context& context() { return context_; }\n"
        "    const Context& context() const { return context_; }\n\n");
}

// The private member, seeded by Context's own member initialisers.
QString contextMemberLine() {
    return QStringLiteral("    Context context_;  // extended state -- seeded by Context's own initialisers\n");
}



GenModel buildModel(const Machine& machine, const QString& rootNamespace) {
    GenModel model;
    model.machineNs = sanitizeSnakeCase(machine.name);
    model.machinePascal = sanitizeIdentifier(machine.name, true);
    // First: the hook-collection loops below read hasContext.
    model.context = machine.context;
    model.hasContext = !machine.context.isEmpty();
    model.hasTypes = !machine.types.isEmpty() || !machine.externalHeaders.isEmpty();
    for (const ContextVariable& variable : machine.context) {
        model.hasStringContext = model.hasStringContext || variable.type == ContextType::String || variable.type == ContextType::Object;
    }

    // Before the transitions loop, which needs the invoke maps.
    for (const State& state : machine.states) {
        const auto invocations = state.effectiveInvocations();
        if (invocations.isEmpty()) {
            continue;
        }
        model.hasInvoke = true;
        QStringList effIds;
        for (const Invocation& inv : invocations) {
            const QString effId = effectiveInvocationId(inv);
            if (effId.isEmpty()) {
                continue;
            }
            effIds.push_back(effId);
            if (!model.invokeOutputTypeByEffectiveId.contains(effId)) {
                // First declaration wins, including its output type.
                model.invokeIdOrder.push_back(effId);
                model.invokeOutputTypeByEffectiveId.insert(effId, inv.outputType);
            }
        }
        if (!effIds.isEmpty()) {
            model.invokeEffectiveIdByStateId.insert(state.id, effIds.first());
            model.invokeEffectiveIdsByStateId.insert(state.id, effIds);
        }
    }

    QStringList nsParts;
    for (const QString& part : rootNamespace.split(QStringLiteral("::"), Qt::SkipEmptyParts)) {
        nsParts.push_back(part);
    }
    if (!model.machineNs.isEmpty()) {
        nsParts.push_back(model.machineNs);
    }
    if (nsParts.isEmpty()) {
        // Never emit an anonymous namespace; the validator blocks this case
        // from reaching disk anyway.
        nsParts.push_back(QStringLiteral("generated_machine"));
    }
    model.nsJoined = nsParts.join(QStringLiteral("::"));

    QString firstStateIdent;
    QString initialIdent;
    for (const State& state : machine.states) {
        const QString ident = sanitizeIdentifier(state.name, true);
        model.stateIdentById.insert(state.id, ident);
        if (firstStateIdent.isEmpty()) {
            firstStateIdent = ident;
        }
        if (state.id == machine.initialStateId) {
            initialIdent = ident;
        }
    }
    // The first-state fallback only matters for an invalid machine.
    model.defaultStateIdent = !initialIdent.isEmpty() ? initialIdent : firstStateIdent;

    for (const Transition& transition : machine.transitions) {
        const QString event = transition.event.trimmed();
        // onDone/onError rows are recognised structurally, never by event
        // text, and kept out of the public event vocabulary.
        const InvokePayloadKind payloadKind = invokePayloadKindForTransition(machine, transition);
        const bool hasEventPayload = !eventPayloadCppTypeForTransition(machine, transition).isEmpty();
        if (payloadKind == InvokePayloadKind::None) {
            if (!event.isEmpty()) {
                if (!model.eventTransitions.contains(event)) {
                    model.eventOrder.push_back(event);
                    model.eventStructNameByRaw.insert(event, sanitizeIdentifier(event, true) + QStringLiteral("Requested"));
                    model.eventMethodByRaw.insert(event, sanitizeIdentifier(event, false) + QStringLiteral("Requested"));
                }
                model.eventTransitions[event].push_back(&transition);
                if (hasEventPayload && !model.eventPayloadTypeByRaw.contains(event)) {
                    model.eventPayloadTypeByRaw.insert(event, transition.payloadType);
                }
            }
        } else if (payloadKind == InvokePayloadKind::Output) {
            model.onDoneByState[transition.from].push_back(&transition);
        } else {
            model.onErrorByState[transition.from].push_back(&transition);
        }
        // Every transition's guard, blank-event (delayed) ones included, but
        // only hook guards; expression guards compile inline.
        const bool payloadInScope = (payloadKind != InvokePayloadKind::None) || hasEventPayload;
        if (guardIsHook(model, transition.guard, payloadInScope)) {
            model.guards.add(transition.guard);
        }
    }
    const auto collectAction = [&](const QString& action, bool payloadInScope = false) {
        const expr::SendToForm sendToForm = expr::parseSendToForm(action);
        if (sendToForm.ok) {
            model.actions.addCustom(action, QStringLiteral("sendTo_%1_%2").arg(sendToForm.target, sendToForm.event));
            return;
        }
        const expr::SendParentForm sendParentForm = expr::parseSendParentForm(action);
        if (sendParentForm.ok) {
            model.actions.addCustom(action, QStringLiteral("sendParent_%1").arg(sendParentForm.event));
            return;
        }
        if (actionIsHook(model, action, payloadInScope)) {
            model.actions.add(action);
        }
    };

    for (const Transition& transition : machine.transitions) {
        const bool payloadInScope = (invokePayloadKindForTransition(machine, transition) != InvokePayloadKind::None) ||
                                    !eventPayloadCppTypeForTransition(machine, transition).isEmpty();
        collectAction(transition.action, payloadInScope);
    }
    for (const State& state : machine.states) {
        for (const QString& entryAction : state.entryActions) {
            collectAction(entryAction);
        }
        for (const QString& exitAction : state.exitActions) {
            collectAction(exitAction);
        }
    }

    for (const Transition& transition : machine.transitions) {
        const auto tt = expr::parseTimeTrigger(transition.event);
        if (tt.ok || (transition.event.trimmed().isEmpty() && transition.delayMs > 0)) {
            model.delayedBySource[transition.from].push_back(&transition);
            model.hasScheduler = true;
        }
    }

    for (const Transition& transition : machine.transitions) {
        if (transition.isAlways()) {
            model.hasAlways = true;
            model.alwaysTransitions.push_back(&transition);
        }
    }

    const auto checkRaise = [&](const QString& action) {
        const expr::RaiseForm form = expr::parseRaiseForm(action);
        if (form.ok) {
            model.hasRaise = true;
            bool found = false;
            for (const QString& existing : model.eventOrder) {
                if (existing.compare(form.event, Qt::CaseInsensitive) == 0) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                model.eventOrder.push_back(form.event);
                model.eventStructNameByRaw.insert(form.event, sanitizeIdentifier(form.event, true) + QStringLiteral("Requested"));
                model.eventMethodByRaw.insert(form.event, sanitizeIdentifier(form.event, false) + QStringLiteral("Requested"));
            }
        }
    };
    for (const Transition& transition : machine.transitions) {
        checkRaise(transition.action);
    }
    for (const State& state : machine.states) {
        for (const QString& act : state.entryActions) {
            checkRaise(act);
        }
        for (const QString& act : state.exitActions) {
            checkRaise(act);
        }
    }
    for (const QString& rawEvent : model.eventOrder) {
        model.eventEnumIdentByRaw.insert(rawEvent, sanitizeIdentifier(rawEvent, true));
    }

    // ---- hierarchical topology (always built) --------------------------------
    for (int i = 0; i < machine.states.size(); ++i) {
        model.stateIndexById.insert(machine.states[i].id, i);
    }
    const auto indexOfId = [&model](quint64 id) -> int {
        return id == 0 ? -1 : model.stateIndexById.value(id, -1);
    };
    model.hierStates.reserve(machine.states.size());
    for (const State& state : machine.states) {
        HierState hs;
        hs.parentIndex = indexOfId(state.parentId);
        hs.depth = depthOfId(machine, state.id);
        hs.initialChildIndex = indexOfId(state.initialChildId);
        hs.isParallel = (state.kind == StateKind::Parallel);
        model.hierStates.push_back(hs);
    }
    model.hierTransitions.reserve(machine.transitions.size());
    for (const Transition& transition : machine.transitions) {
        HierTransition ht;
        ht.sourceIndex = indexOfId(transition.from);
        ht.declaredTargetIndex = indexOfId(transition.to);
        ht.reenter = transition.reenter;
        ht.always = transition.isAlways();
        ht.isMultiTarget = transition.isMultiTarget();
        if (transition.isMultiTarget()) {
            model.hasMultiTarget = true;
            for (quint64 tid : transition.targets) {
                ht.targetIndices.push_back(indexOfId(tid));
            }
            ht.targetIndex = ht.targetIndices.isEmpty() ? -1 : ht.targetIndices.first();
            ht.lccaIndex = indexOfId(lccaId(machine, transition.from, transition.targets));
            ht.historyPolicy = HierHistoryRedirect::None;
        } else if (transition.to != 0) {
            // A History target enters through its parent compound (static
            // topology; the validator guarantees the parent exists).
            quint64 effectiveTargetId = transition.to;
            HierHistoryRedirect policy = HierHistoryRedirect::None;
            const State* dest = findStateById(machine, transition.to);
            if (dest && dest->kind == StateKind::History) {
                effectiveTargetId = dest->parentId;
                policy = dest->historyDeep ? HierHistoryRedirect::AllLevels : HierHistoryRedirect::OneLevel;
            }
            ht.targetIndex = indexOfId(effectiveTargetId);
            ht.lccaIndex = indexOfId(lccaId(machine, transition.from, effectiveTargetId));
            ht.historyPolicy = policy;
        }
        model.hierTransitions.push_back(ht);
    }
    // Same first-state fallback as defaultStateIdent, as an index.
    int initialIndex = -1;
    for (int i = 0; i < machine.states.size(); ++i) {
        if (machine.states[i].id == machine.initialStateId) {
            initialIndex = i;
            break;
        }
    }
    model.initialStateIndex = (initialIndex != -1) ? initialIndex : (machine.states.isEmpty() ? -1 : 0);

    return model;
}



QString stateIdent(const GenModel& model, quint64 stateId) {
    return model.stateIdentById.value(stateId, QStringLiteral("Unknown"));
}

}  // namespace app
